name: Playwright Cocktail API Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test:regression
    - name: Debug Check if Allure results exist
      run: |
          if [ ! -d "allure-results" ]; then
            echo "ERROR: allure-results directory not found!"
            exit 1
          fi
          echo "Allure results exist."

    - name: Generate Allure Report
      run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

    - name: Check if Allure report exists
      run: |
          if [ ! -d "allure-report" ]; then
            echo "ERROR: allure-report directory not found!"
            exit 1
          fi
          echo "Allure report generated successfully."

    - name: Deploy Allure Report to GitHub Pages
      run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fd
          mv allure-report/* .
          git add .
          git commit -m "Deploy Allure report"
          git push -f https://${{ secrets.GH_PAT }}@github.com/automation9006/typescript-cocktail-api-tests.git gh-pages

